### ISSUE TITLE
Enabler: (DIFFERENT REPO)Make API for Mapping Lookups

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform-dynamic-services#6]
# Title of Enabler

Need to support 
* pretty-url-name -> C-Code
* C-Code -> Pretty Url & Term Text
* Need to support our override logic...

Possible Approach: 
* Just make a lot of json files, and I mean a lot. Put on netstorage.
* Expose the CDE logic for the lookup as a Legacy CDE Service.

So this will leverage a lot of the work in the CDE, but it is going to be messy. 

This is going to wrap a lot of the logic in 
* C-Codes -> Pretty URL: https://github.com/NCIOCPL/wcms-cde/blob/master/CDESites/CancerGov/SiteSpecific/Modules/CancerGov.BasicCTSv2/SnippetControls/TrialListings/DynamicTrialListingPageControl.cs#L346
* C-Code -> Display Name: https://github.com/NCIOCPL/wcms-cde/blob/master/CDESites/CancerGov/SiteSpecific/Modules/CancerGov.BasicCTSv2/SnippetControls/TrialListings/DynamicTrialListingPageDiseaseControl.cs#L138

However, after looking at that code it will be easier to take some of the algorithm, but write it from scratch with a new source of data.

> **ESTIMATE** 2 weeks, this may go longer if the code will not easily allow for this.

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* References: *URL to web site with examples*
* Web Page: *Here goes a URL to an existing web page*

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Sub-Tasks
- [ ] Create Mapping Files to use
- [ ] Create Wrapper around those files.

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by blairlearn** [comment]
This ended up being implemented in the [Clinical Trials Listing Support API](https://github.com/NCIOCPL/clinical-trials-listing-api).
