### ISSUE TITLE
Acceptance tests for glossary href handler

### ISSUE THREAD

**Issue by kate-mashkina** [NCIOCPL/cgov-digital-platform-dynamic-services#8]
**Parent Issue:** #3 

### Sub-Tasks
- [ ] init Node.js project
- [ ] configure cypress and cucumber-preprocessor
- [ ] add integration tests

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction
